from Programmer import *
from ProgramVisitor import ProgramVisitor
from StateManager import StateManager
from QOperator import QOperator
from ExprTransformer import ExprTransformer
from typing import List, Optional
from TypeChecker import *
from StateChecker import *

def envPrint(env:tuple):
    printer = PrettyPrinter()
    lines = []
    for (loci, ty, st, num) in env:
        loci_str = " ".join(loc.accept(printer) for loc in loci)
        ty_str = ty.accept(printer)
        if st:
            st_str = st.accept(printer)
        lines.append(f"Env ⊢ {num} : {loci_str}: {ty_str} ↦ {st_str}")
    print("\n", "\n".join(line for line in lines))


class SymbolicExecutor(ProgramVisitor):
    def __init__(self, kenv=None, tenv=None, senv=None):
        super().__init__()
        # kind env, can be generated by CollectKind.
        # mapping from function names to mappings.
        # each mapping is a map from variables to kinds in a method.
        # different methods have different mapping
        self.kenv = kenv
        # type env, can be generated by TypeCollector
        # mapping from function names to two lists of pairs.
        # each list contains pairs of a locus and a type
        # meaning that the locus has a certain type
        # different loci in a list are disjoint
        # there are two lists for each function name
        # The first list contains the type information for the loci at the input
        # The second list contains the type information for the loci at the output location
        self.tenv = tenv

        self.senv = senv
        # fkenv a kind env in a function.
        # in visitMethod, we find out the kind-env for the fun-name.
        self.fkenv = None
        #ftenvp gets the locus-list at the input position of a function
        self.ftenvp = None
        # ftenvr gets the locus-list at the output position of a function
        self.ftenvr = None
        #varnums is the locus-list at the input position
        #There is an additional field for each pair (like now it is not a pair, but triple)
        #The third field iin a triple is a generated identifier (a number) to identify the specific locus
        self.varnums = None
        #outvarnums is the locus-list at the ouput position
        self.outvarnums = None
        #The sizemap is for used inside a function
        #This sizemap maps a range in a locus to its size
        #like x[i,j) has the size j - i
        self.sizemap = dict()
        #The counter generates a new identifier for a locus,
        #When generating a locus ID, we increment the counter
        self.counter = 0
        #The function name when visiting a method
        self.fvar = ""
        #For a locus in a spec, we generate Dafny variables for each range in a locus,
        #depending on the types
        #For example, if x[i,j) , y[0,n) |-> en(1).
        #In Qafny, the variables x and y have no extra number identifier, because it is unnecessary
        #In Dafny, each instruction/function call will generate new seq variables
        #So, we need to always generate different new instances for x and y
        #So, for a spec, we will call the counter to generate the new identifier
        #and the Dafny variable for the locus is DVar(x,counter), DVar(y,counter),
        # DVar(amp,counter), and DVar(phase,counter)
        # The variables are also associated with types, and depend on types
        #Now, the DVars above have type seq<real> or seq<seq<bv1>>
        # if we have a en(2) type above, we will have seq<seq<real>> and seq<seq<seq<bv1>>>
        self.qvars = []
        #When analyzing a locus in a specific plance
        #We assign the locus to the global field in the visitor class
        #This will reserves the locus and allow the sub-visitor-call to assign the current locus
        self.locus = []
        self.state_manager = StateManager()
        self.operator = QOperator(self.state_manager)

    def genVarNumMap(self, senv: list[(list[QXQRange], QXQTy)]):
        tmp = []
        for locus, qty, st in senv:
            tmp = tmp + [(locus, qty, st, self.counter)]
            self.counter += 1
        return tmp

    def upvar(self, var: str):
        tmp = self.varnums.get(var)
        self.varnums.update({var:self.varnums.get(var)+1})
        return tmp

    def calRange(self, v: QXCRange):
        '''Converts a QXCRange to a QXAExpr that represents the length of the q-bit array.'''
        if isinstance(v.left(), QXNum) and v.left().num() == 0:
            return v.right() #this is QXBind(id=n)
        return QXBin("-", v.right(), v.left())

    def genSizeMap(self):
        self.sizemap = dict()
        for locus, qty, st, num in self.varnums:
            for elem in locus:
                v = self.calRange(elem.crange())
                self.sizemap.update({(elem.ID(), num):v})

    def removeLocus(self, n:int):
        vs = []
        for i in range(len(self.varnums)):
            locus,qty,st,num = self.varnums[i]
            if n == num:
                vs += self.varnums[i+1:len(self.varnums)]
                break
            else:
                vs += [(locus,qty,st,num)]

        self.varnums = vs


    def replaceType(self, n:int, t:QXQTy):
        vs = []
        for i in range(len(self.varnums)):
            locus,qty,st,num = self.varnums[i]
            if n == num:
                vs += [(locus,t,num)]+self.varnums[i+1:len(self.varnums)]
                break
            else:
                vs += [(locus,qty,st,num)]

        self.varnums = vs

    def updateOutVarNums(self, qstmt):
        if (isinstance(qstmt, QXQAssign) or isinstance(qstmt, QXCast)):
                            for i in range(len(self.outvarnums)):
                                loc, qty, st, num = self.outvarnums[i]
                                if compareLocus(qstmt.locus(), loc) or compareLocus(qstmt.locus(), loc) == []:
                                    self.outvarnums[i] = loc, qty, st, self.counter

    def visitMethod(self, ctx: QXMethod):
        """Entry point for symbolic execution"""
        # Process specifications

        self.fvar = str(ctx.ID())
        self.fkenv = self.kenv.get(self.fvar)
        
        self.ftenvp = self.tenv.get(self.fvar)[0]
        # ftenvr is initialized to type env of the ensures clause
        self.ftenvr = self.tenv.get(self.fvar)[1]

        self.fsenvp = self.senv.get(self.fvar)[0]
        # ftenvr is initialized to type env of the ensures clause
        self.fsenvr = self.senv.get(self.fvar)[1]


        print(f"\nVisiting method {self.fvar} with input senv: {self.fsenvp} \nand output senv: {self.fsenvr}")
        #generate varnums for the input tenv
        #varnums is a list of triples (locus, type, counter)
        self.varnums = self.genVarNumMap(self.fsenvp)
        print(f"\nMethod {self.fvar} with input varnums: {self.varnums}")
        self.outvarnums = self.genVarNumMap(self.fsenvr)
        self.genSizeMap()
    #    print(f"sizemap for {self.fvar}: {self.sizemap}")

        for bind in ctx.bindings():
            if isinstance(bind.type(), TySingle):
                self.state_manager.set_pre_bind(bind)

        for cond in ctx.conds():
            if isinstance(cond, QXRequires):
                if isinstance(cond.spec(), QXQSpec):
                    self.state_manager.set_precond_q(cond.spec())
                elif isinstance(cond.spec(), QXComp):
                    self.state_manager.set_precond_c(cond.spec())

            elif isinstance(cond, QXEnsures):
                if isinstance(cond.spec(), QXQSpec):
                    self.state_manager.set_postcond_q(cond.spec())
                elif isinstance(cond.spec(), QXComp):
                    self.state_manager.set_postcond_c(cond.spec())
#                print(f"\n SymEx Postcondition: {cond.spec()}")
        self.state_manager.init_snapshot()
    #    print(self.state_manager.show_history())
 #       print(f"\n check here: {self.tenv[self.fvar]} {len(self.tenv[self.fvar])}")
        # Process statements
        axiom = ctx.axiom()
        if not axiom:
            tc = TypeChecker(self.kenv, self.tenv, self.varnums, self.counter)
            sc = StateChecker(self.kenv, self.tenv, self.senv, self.varnums, self.counter)
            i = 0
            for stmt in ctx.stmts():
                print(f"\nVisiting statement {i}: {stmt}")
                print(f"\n {i} before: {sc.renv}")
                envPrint(sc.renv)
                stmt.accept(sc)
                print(f"\n after: {sc.renv}")
                envPrint(sc.renv)
                i += 1
                

            print(self.state_manager.show_history())
            print(f"\noutput varnums:{self.outvarnums}")
    
    
    #assertions should be inconsistent of variable bindings
    def visitAssert(self, ctx: QXAssert):
        """Capture (sp, assertion) for later property-based testing, with type checking."""
        spec = ctx.spec()
        sp = self.state_manager.get_curr_bind()
        assertion = {}

        # Quantum assertion
        if isinstance(spec, QXQSpec):
            # Type check the assertion locus/type
            if self.kenv is not None and self.tenv is not None:
                renv = [(spec.locus(), spec.qty(), 0)]
                print(f"Type-checking quantum assertion with renv: {renv}")
                tc = TypeChecker(self.kenv, self.tenv, renv, 0)
                tc.visitQSpec(spec)  # Type-check the assertion

            quantum_env = sp.get("quantum", {})
            assertion['quantum'] = {}

            # For each QXQRange in the assertion, match both variable name and range
            for rng in spec.locus():
                var = rng.ID()
                for env_var, (env_loci, env_ty, env_state) in quantum_env.items():
                    # Use your compareLocus from TypeChecker/ProgramTransfer for robust matching
                    from ProgramTransfer import compareLocus
                    if compareLocus([rng], env_loci) == []:
                        # Store the assertion's own locus/type/state
                        assertion['quantum'][env_var] = ([rng], spec.qty(), spec.state())

        # Classical assertion
        elif isinstance(spec, QXComp):
            # Type check the classical assertion
            if self.kenv is not None and self.tenv is not None:
                tc = TypeChecker(self.kenv, self.tenv, [], 0)
                tc.visitBool(spec)
    
                

            var = spec.left().ID() if hasattr(spec, "left") and isinstance(spec.left(), QXBind) else None
            env_classical_vars = set(sp.get("classical", {}).keys())
            if var and var in env_classical_vars:
                assertion['classical'] = {var: (None, spec)}
            else:
                assertion['classical'] = {}

        else:
            print(f"Unknown assertion type: {type(spec)}")
            return

        self.assertions.append((sp, assertion))
        print(f"Captured assertion at this point in the program:\n  Assertion: {assertion}\n  Symbolic state: {sp}")

    def visitQAssign(self, ctx: QXQAssign):
        """Handle quantum assignment q *= qexp"""
        regs = [loc.ID() for loc in ctx.locus()]
        qexp = ctx.exp()
        print(f"\nVisiting quantum assignment: {regs} *= {qexp}")
        
        if isinstance(qexp, QXOracle):
            self.operator.apply_lambda(regs, qexp)
        elif isinstance(qexp, QXSingle):
            if qexp.op() == 'H':
                self.operator.apply_hadamard(regs, qexp)
            elif qexp.op() == 'QFT':
                self.operator.apply_qft(regs, qexp)
            elif qexp.op() == 'RQFT':
                self.operator.apply_rqft(regs, qexp)
        else:
            self.operator.apply_mea(regs, qexp)

    def visitCast(self, ctx: QXCast):
        
        """Handle quantum cast"""
        # Process quantum type
        print(f"\nVisiting cast: {ctx.qty()}")
        regs = [loc.ID() for loc in ctx.locus()]
        self.operator.apply_cast(regs, ctx.qty())
          

    #think visitIf as a Control-U
    def visitIf(self, ctx: QXIf):
        #need to consider the variable binding,
        #because the conditional operation eat variables

        """Handle if statement"""
        # Add path condition
        self.state_manager.add_path_cond(ctx.bexp())
       
        # Process then branch
        for stmt in ctx.stmts():
     #       print(f"symex: {self.state_manager.path_conds}")
            self.visit(stmt)
            
        # Pop path condition after processing
        self.state_manager.remove_path_cond()
